version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: jimenarioja
      POSTGRES_PASSWORD: jimena
      POSTGRES_DB: public
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
