PROJECT_NAME = "jimena-core"
PROJECT_VERSION = "0.0.1"
AUTHOR = "jimena-rioja"
AUTHOR_EMAIL = "jimenarioja30@gmail.com"
DESCRIPTION = "Set of functionalities to process and filter data"
LONG_DESCRIPTION_CONTENT_TYPE = "text/markdown"
URL = "https://github.com/jimrioja/jimena-core"
PYTHON_REQUIRES = ">=3.9"
REQUIREMENTS_FILE = "requirements.txt"

IMAGE = "postgres"
DATA_BASE_URL = ""
LOCAL_DATA_BASE = ""
REQUIREMENTS = ""

TESTS = "tests"
RESOURCES = "resources"
COMPONENTS = "components"

FILENAME = "jimena-core/infra/docker/postgres/docker_compose/postgres_data/data.ini"
SECTION = "postgresql"
